spring:
  application:
    name: storage
  datasource:
    url: url
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
server:
  servlet:
    contextPath: /storage
params:
  secretkey: Test$Secret$Key0